spring:
  datasource:
    url: jdbc:mysql://${DB_HOST_E2E}:${DB_PORT_E2E}/${DB_NAME_E2E}?createDatabaseIfNotExist=true
    username: ${DB_USER_E2E}
    password: ${DB_PASSWORD_E2E}


cors:
  allowedOrigins: ${CLIENT_URL_DEV}
