spring:
  datasource:
    url: jdbc:mysql://mysql:3307/testdb?createDatabaseIfNotExist=true
    username: testuser
    password: testpass

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

cors:
  allowedOrigins: http://localhost:4200
